apiVersion: v2
name: print2pdf-go
description: A Helm chart for deploying Print2PDF
type: application
sources:
  - https://github.com/chialab/print2pdf-go
maintainers:
  - name: Chialab
version: 0.5.4
appVersion: "0.5.4"
